print("Exercise 2.-")
print("La suma de 3+4 es = ", 3+4)
print("La resta de 3-4 es = ", 3-4)
print("La multiplicacion de 3*4 es = ", 3*4)
print("La division de 3/4 es = ", 3/4)
print("El exponencial de 3 a la 4 es = ", 3**4)
print(3//4)
print(3%4)
print("\nExercise 3.-")
print("My name is Sebastian")
print("My family name is Trejo")
print("My country is Mexico")
print("I am enjoying 30 days of python")
print("\nExercise 4.-")
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type('Asabeneh'))
print(type('Sebastian'))
print(type('Trejo'))
print(type('Mexico'))